# Generated by Django 2.2.1 on 2019-06-27 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saloon_name', models.CharField(max_length=20, null=True)),
                ('event_name', models.CharField(blank=True, max_length=15, null=True)),
                ('Event_type', models.CharField(blank=True, choices=[('فوتبال', 'فوتبال'), ('تنیس', 'تنیس'), ('بسکتبال', 'بسکتبال'), ('والیبال', 'والیبال'), ('پینتبال', 'پینتبال'), ('بازی های کامپیوتری', 'بازی های کامپیوتری'), ('شطرنج', 'شطرنج'), ('دیگر', 'دیگر')], max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('man', 'man'), ('Female', 'Female')], max_length=5, null=True)),
                ('state', models.CharField(blank=True, choices=[('البرز', 'البرز'), ('تهران', 'تهران'), ('خراسان شمالی', 'خراسان شمالی'), ('اصفهان', 'اصفهان')], max_length=20, null=True)),
                ('City', models.CharField(blank=True, choices=[('کرج', 'کرج'), ('تهران', 'تهران'), ('مشهد', 'مشهد'), ('اصفهان', 'اصفهان')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=700, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('needed', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_event.Event')),
                ('name_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
