# Generated by Django 2.2.1 on 2019-06-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0002_auto_20190627_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
