# Generated by Django 2.2.1 on 2019-06-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0004_remove_event_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
