# Generated by Django 2.2.1 on 2019-06-30 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0006_confrim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confrim',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrim', to=settings.AUTH_USER_MODEL),
        ),
    ]
