# Generated by Django 2.2.1 on 2019-07-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0009_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept',
            name='event',
        ),
        migrations.AddField(
            model_name='accept',
            name='confrim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept', to='app_event.Confrim'),
        ),
    ]
