# Generated by Django 2.2.1 on 2019-07-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0010_auto_20190701_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept',
            name='confrim',
        ),
        migrations.AddField(
            model_name='accept',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Accept', to='app_event.Event'),
        ),
    ]
