# Generated by Django 2.2.1 on 2019-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0011_auto_20190701_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='confrim',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
