# Generated by Django 2.2.1 on 2019-07-05 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0019_auto_20190705_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confrim',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
