# Generated by Django 2.2.1 on 2019-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0020_auto_20190705_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confrim',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
