# Generated by Django 2.2.1 on 2019-07-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0022_auto_20190705_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_event.Event'),
        ),
    ]
