# Generated by Django 2.2.1 on 2019-07-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0023_auto_20190707_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accept',
        ),
    ]
