# Generated by Django 2.2.1 on 2019-07-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0024_delete_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accept_user',
            field=models.TextField(null=True),
        ),
    ]
