# Generated by Django 2.2.1 on 2019-07-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0025_event_accept_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accept_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
