# Generated by Django 2.2.1 on 2019-08-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0026_auto_20190730_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accept_user',
        ),
    ]
