# Generated by Django 2.2.1 on 2019-08-02 13:20

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0027_remove_event_accept_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
