# Generated by Django 2.2.1 on 2019-08-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0028_auto_20190802_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
