# Generated by Django 2.2.1 on 2019-08-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0029_auto_20190802_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='period_of_time',
            field=models.IntegerField(null=True),
        ),
    ]
