# Generated by Django 2.2.1 on 2019-10-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0033_auto_20190919_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='create_time',
            new_name='datetime',
        ),
    ]
