# Generated by Django 2.2.1 on 2019-11-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_event', '0035_auto_20191027_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('send_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('resiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_event.Event')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
