# Generated by Django 2.2.1 on 2019-11-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_event', '0037_auto_20191105_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(null=True)),
                ('block', models.CharField(choices=[('راهنمایی', 'راهنمایی'), ('همکاری', 'همکاری'), ('مدیریت', 'مدیریت'), ('سایر موارد', 'سایر موارد')], max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
