# Generated by Django 2.2.1 on 2019-11-08 19:38

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0038_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='id_support',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
