# Generated by Django 2.2.1 on 2019-11-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0039_auto_20191108_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name_plural': 'پشتیبانی'},
        ),
        migrations.RemoveField(
            model_name='support',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='support',
            name='id_support',
        ),
    ]
