# Generated by Django 2.2.1 on 2019-11-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0041_auto_20191112_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='id_support',
        ),
    ]
