# Generated by Django 2.2.1 on 2019-12-17 23:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0043_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Possibilities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('بوفه', 'بوفه'), ('سرویس بهداشتی', 'سرویس بهداشتی'), ('دوش و کمد', 'دوش و کمد'), ('رختکن', 'رختکن'), ('پارکینگ', 'پارکینگ'), ('فروشگاه', 'فروشگاه'), ('تهویه هوا', 'تهویه هوا'), ('فضای سبز', 'فضای سبز'), ('ماساژ', 'ماساژ'), ('جایگاه تماشاچیان', 'جایگاه تماشاچیان'), ('توپ', 'توپ'), ('مربی', 'مربی')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(blank=True, choices=[('اقایان', 'اقایان'), ('بانوان', 'بانوان')], max_length=30, null=True),
        ),
    ]
