# Generated by Django 2.2.1 on 2019-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0044_auto_20191217_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
