# Generated by Django 2.2.1 on 2019-12-17 23:58

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0045_auto_20191217_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
