# Generated by Django 2.2.1 on 2019-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0046_auto_20191217_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(blank=True, choices=[('آقایان', 'آقایان'), ('بانوان', 'بانوان')], max_length=30, null=True),
        ),
    ]
