# Generated by Django 2.2.1 on 2019-06-27 07:38

import app_profile.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tell', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0][9][0-3][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$')])),
                ('Verify_code', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=app_profile.models.get_upload_path)),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=11, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0][9][0-3][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$')])),
                ('birth_date', django_jalali.db.models.jDateField(null=True)),
                ('bio', models.TextField(blank=True, max_length=400, null=True)),
                ('instagram', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('tell', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0][9][0-3][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$')])),
                ('Verify_code', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
