# Generated by Django 2.2.1 on 2019-06-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_auto_20190627_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verify',
        ),
    ]
