# Generated by Django 2.2.1 on 2019-07-30 10:36

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_delete_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
