# Generated by Django 2.2.1 on 2019-08-15 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0006_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='resiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messager', to='app_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messager', to=settings.AUTH_USER_MODEL),
        ),
    ]
