# Generated by Django 2.2.1 on 2019-08-15 17:33

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0010_auto_20190815_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='send_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
    ]
