# Generated by Django 2.2.1 on 2019-08-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0012_auto_20190817_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'پیام ها'},
        ),
    ]
