# Generated by Django 2.2.1 on 2019-09-16 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0018_messages_pk_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tell', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0][9][0-3][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$')])),
                ('messages', models.CharField(max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
