# Generated by Django 2.2.1 on 2019-09-20 12:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0020_auto_20190916_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('فوتبال', 'فوتبال'), ('تنیس', 'تنیس'), ('بسکتبال', 'بسکتبال'), ('والیبال', 'والیبال'), ('پینتبال', 'پینتبال'), ('بازی های کامپیوتری', 'بازی های کامپیوتری'), ('شطرنج', 'شطرنج'), ('دیگر', 'دیگر')], max_length=200, null=True),
        ),
    ]
