# Generated by Django 2.2.1 on 2019-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0022_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orgin_fav',
            field=models.CharField(blank=True, choices=[('فوتبال', 'فوتبال'), ('تنیس', 'تنیس'), ('بسکتبال', 'بسکتبال'), ('والیبال', 'والیبال'), ('پینتبال', 'پینتبال'), ('بازی های کامپیوتری', 'بازی های کامپیوتری'), ('شطرنج', 'شطرنج'), ('دیگر', 'دیگر')], max_length=20, null=True),
        ),
    ]
