# Generated by Django 2.2.1 on 2019-10-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0023_profile_orgin_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='pk_message',
        ),
    ]
