# Generated by Django 2.2.1 on 2019-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0029_auto_20191104_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='resiver',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
