# Generated by Django 2.2.1 on 2019-11-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0034_auto_20191105_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messages',
        ),
    ]
