# Generated by Django 2.2.1 on 2019-12-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0035_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
