# Generated by Django 2.2.1 on 2019-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0036_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tell',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tell',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
