# Generated by Django 2.2.1 on 2019-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20190829_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='descript',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
