# Generated by Django 2.2.1 on 2019-09-15 15:06

import app_blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0007_blog_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('descript', models.CharField(max_length=80, null=True)),
                ('create_time', django_jalali.db.models.jDateField(auto_now_add=True, null=True)),
                ('content', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField(max_length=40)),
                ('image', models.ImageField(null=True, upload_to=app_blog.models.landing_img)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
