# Generated by Django 2.2.1 on 2019-10-01 10:57

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_auto_20190929_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='app_blog.Blog'),
        ),
    ]
