# Generated by Django 2.2.1 on 2019-10-07 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0012_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='create_time',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rep',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
