# Generated by Django 2.2.1 on 2019-10-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0013_auto_20191007_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep',
            name='com',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='user',
        ),
    ]
