# Generated by Django 2.2.1 on 2019-10-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0015_auto_20191007_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep_cm',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_blog.Blog'),
        ),
    ]
