# Generated by Django 2.2.1 on 2019-11-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0016_rep_cm_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
