# Generated by Django 2.2.1 on 2019-06-27 07:39

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(blank=True, max_length=30, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0][9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$')])),
                ('city', models.CharField(blank=True, choices=[('کرج', 'کرج'), ('تهران', 'تهران')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('salon_type', models.CharField(blank=True, choices=[('Football', 'Football hall'), ('Tennis', 'Tennis'), ('basketball', 'basketball'), ('Volleyball', 'Volleyball'), ('paintball', 'paintball'), ('جند منطوره', 'چند منظوره')], max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('اقایان', 'اقایان'), ('خانم ها', 'خانم ها'), ('خانم ها واقایان', 'خانم ها واقایان')], max_length=15, null=True)),
                ('Possibilities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('بوفه', 'بوفه'), ('سرویس بهداشتی', 'سرویس بهداشتی'), ('دوش و کمد', 'دوش و کمد'), ('رختکن', 'رختکن'), ('پارکینگ', 'پارکینگ'), ('فروشگاه', 'فروشگاه'), ('تهویه هوا', 'تهویه هوا'), ('فضای سبز', 'فضای سبز'), ('ماساژ', 'ماساژ'), ('جایگاه تماشاچیان', 'جایگاه تماشاچیان'), ('توپ', 'توپ'), ('مربی', 'مربی')], max_length=20, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', django_jalali.db.models.jDateField(null=True)),
                ('cash', models.IntegerField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('burn', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
