# Generated by Django 2.2.1 on 2019-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0002_remove_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='salon_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
