# Generated by Django 2.2.1 on 2019-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0003_auto_20191113_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
