# Generated by Django 2.2.1 on 2019-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0005_auto_20191113_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='salon_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
