# Generated by Django 2.2.1 on 2019-11-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0006_auto_20191113_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='salon_roof',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
