# Generated by Django 2.2.1 on 2019-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0010_comment_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_salon',
            name='star',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
