# Generated by Django 2.2.1 on 2019-11-28 14:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0011_comment_salon_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_salon',
            name='star',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='Possibilities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('بوفه', 'بوفه'), ('سرویس بهداشتی', 'سرویس بهداشتی'), ('دوش و کمد', 'دوش و کمد'), ('رختکن', 'رختکن'), ('پارکینگ', 'پارکینگ'), ('فروشگاه', 'فروشگاه'), ('تهویه هوا', 'تهویه هوا'), ('فضای سبز', 'فضای سبز'), ('ماساژ', 'ماساژ'), ('جایگاه تماشاچیان', 'جایگاه تماشاچیان'), ('توپ', 'توپ'), ('مربی', 'مربی')], max_length=120, null=True),
        ),
    ]
