# Generated by Django 2.2.1 on 2019-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0014_auto_20191128_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_salon',
            name='star',
            field=models.PositiveSmallIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
