# Generated by Django 2.2.1 on 2019-11-29 13:11

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0016_auto_20191128_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
    ]
