# Generated by Django 2.2.1 on 2019-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0017_reserve_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
