# Generated by Django 2.2.1 on 2019-12-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0018_reserve_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='address',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='salon_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
