# Generated by Django 2.2.1 on 2019-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserve', '0019_auto_20191221_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='salon_sport',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
